services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"    # HTTPS
      - "81:81"     # NPM Admin UI
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    networks:
      - proxy
  duckdns-updater:
    image: linuxserver/duckdns
    container_name: duckdns-updater
    restart: unless-stopped
    env_file:
      - ./duckdns-updater/.env
    volumes:
      - duckdns-data:/config
    networks:
      - proxy
  mediaflow_proxy:
    image: qwertyuiop8899/mediaflow-proxy:latest
    container_name: mediaflow_proxy
    env_file:
      - ./mfp/.env
    restart: unless-stopped
    networks:
      - proxy
 #stremio-docker:
  #  image: tsaridas/stremio-docker:latest
  #  container_name: stremio-docker
  #  ports:
  #    - "8080:8080"
  #    - "11470:11470"
  #  environment:
  #    - NO_CORS=1
  #    - CASTING_DISABLED=1
  #  restart: unless-stopped
  #  networks:
  #    - proxy

volumes:
  npm-data:
  npm-letsencrypt:
  duckdns-data:

networks:
  proxy:
    external: true
